### ISSUE TITLE
Examle not working

### ISSUE THREAD

**Issue by madamadami** [maxvst/python-selenium-chrome-html-to-pdf-converter#2]
I installed everything as described, but if I run the example, I get this message:

```
(venv) admin@mac examples % python3 converter.py https://pythonbasics.org pb.pdf

Traceback (most recent call last):
  File "converter.py", line 10, in <module>
    result = get_pdf_from_html(sys.argv[1], chromedriver='../chromedriver')
  File "../sample/html_to_pdf_converter.py", line 30, in get_pdf_from_html
    result = send_devtools(driver, "Page.printToPDF", calculated_print_options)
  File "../sample/html_to_pdf_converter.py", line 11, in send_devtools
    if response['status']:
KeyError: 'status'
```
Could someone help me by solving this issue?

**Comment by maxvst** [comment]
There was PR https://github.com/maxvst/python-selenium-chrome-html-to-pdf-converter/pull/1 It should solve your problem.
I approved it but I forget to merge it. :( Now everything is OK.
Pull update and try again.
